apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginxmaster
  name: nginxmaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxmaster
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginxmaster
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
